version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.appserver
    ports:
      - "3000:3000"
    environment:
      - WORKER_TYPE=app

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    environment:
      - WORKER_TYPE=rabbitmq
