version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.appserver
    ports:
      - "3000:3000"
    environment:
      - WORKER_TYPE=app

  fileserver:
    build:
      context: .
      dockerfile: Dockerfile.fileserver
    environment:
      - WORKER_TYPE=subscriber
